version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      # Tyto údaje pak použijeme v .env souboru
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432" # Propojení portu uvnitř Dockeru s tvým Macem
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: # Zajišťuje, že se data nesmažou při vypnutí Dockeru